services:
  php:
    build:
      target: development
      args:
        USER_ID: ${SPIN_USER_ID}
        GROUP_ID: ${SPIN_GROUP_ID}
    environment:
        SSL_MODE: mixed
    volumes:
      - '${APP_CODE_PATH_HOST}:/var/www/html/'
    ports:
      - '${HTTP_PORT}:8080'
      - '${HTTPS_PORT}:8443'
    networks:
      - development
    depends_on:
      - mariadb

  node:
    image: node:20
    volumes:
      - '${APP_CODE_PATH_HOST}:/usr/src/app/'
    working_dir: /usr/src/app/
    networks:
      - development

  mariadb:
    image: mariadb:10.11
    networks:
      - development
    volumes:
      - '${APP_CODE_PATH_HOST}/.infrastructure/volume_data/mariadb/database_data/:/var/lib/mysql'
    environment:
        MYSQL_ROOT_PASSWORD: 'rootpassword'
        MYSQL_DATABASE: 'laravel'
        MYSQL_USER: 'mysqluser'
        MYSQL_PASSWORD: 'mysqlpassword'
    ports:
      - '${MYSQL_PORT}:3306'

  mailpit:
      image: axllent/mailpit
      networks:
        - development
      ports:
        - '${MAILPIT_PORT}:8025'

networks:
  development:
